bj photogram industrial 2
borvux/photogram-industrial pull request #2
Opened 2024-07-01 20:58 UTC by borvux

2024-07-01 20:59 UTC, reherr approved these changes
oh woow!

2024-07-01 21:39 UTC, borvux commented
added new commit to fix the validates in the likes model

2024-07-01 21:41 UTC, thierrychau requested changes
See below minor comments! Looks good otherwise

2024-07-01 21:41 UTC, thierrychau commented on app/models/like.rb
> +  has_many :likes, foreign_key: :fan_id
A like has many likes?

2024-07-01 21:41 UTC, thierrychau commented on app/models/photo.rb
> +  has_many :own_photos, foreign_key: :owner_id, class_name: "Photo"
A photo has many own photos?

2024-07-01 21:41 UTC, thierrychau commented on app/models/user.rb
> +  has_many :sent_follow_requests, foreign_key: :sender_id, class_name: "FollowRequest"
We want to avoid a violation of the foreign key constraint if a user is deleted (meaning it's leaving associated FollowRequest records with a sender_it referencing a User who is not longer existing). Can you add a `dependent: :destroy` option here?

2024-07-01 21:58 UTC, borvux commented on app/models/like.rb
> +  has_many :likes, foreign_key: :fan_id
I have deleted line 26

2024-07-01 21:58 UTC, borvux commented on app/models/photo.rb
> +  has_many :own_photos, foreign_key: :owner_id, class_name: "Photo"
I have deleted line 32

2024-07-01 21:59 UTC, borvux commented on app/models/user.rb
> +  has_many :sent_follow_requests, foreign_key: :sender_id, class_name: "FollowRequest"
i have added dependent: :destroy in line 35

2024-07-02 02:28 UTC, thierrychau commented
@borvux did you push your commits? I don't see the changes you mentioned

2024-07-02 02:30 UTC, borvux commented
> @borvux did you push your commits? I don't see the changes you mentioned

I totally forgot to do that, sorry !!!

2024-07-02 03:11 UTC, thierrychau approved these changes
Looks great, good job. Thanks for the edit. Good to merge!

2024-07-02 13:50 UTC, merged